Repository pathintegral-institute/mcpm.sh, pull requests merged in 2025-07, with the labels that each got.

#197 chore: Fix the archived server links for modelcontextprotocol/servers
  mcp-registry/servers/aws-kb-retrieval.json
  mcp-registry/servers/brave-search.json
  mcp-registry/servers/everart.json
  mcp-registry/servers/gitlab.json
  mcp-registry/servers/google-drive.json
  mcp-registry/servers/google-maps.json
  mcp-registry/servers/postgresql.json
  mcp-registry/servers/puppeteer.json
  mcp-registry/servers/sentry.json
  mcp-registry/servers/slack.json
  mcp-registry/servers/sqlite.json
Labels: Review effort 1/5

#214 add support sse for `run` command
  src/mcpm/commands/profile/run.py
  src/mcpm/commands/run.py
Labels: Review effort 3/5, codex-review-completed

#215 [registry]fix: replace hyphen to underscore in server name
  pages/registry/index.html
Labels: Review effort 2/5, codex-review-completed

#219 Fix typo in ElevenLabs API key env variable name
  mcp-registry/servers/elevenlabs-mcp.json
Labels: Review effort 1/5
