Repository pathintegral-institute/mcpm.sh, pull requests merged in 2025-06, with the labels that each got.

#186 feat: support custom node runtime config
  README.md
  README.zh-CN.md
  src/mcpm/commands/config.py
  src/mcpm/commands/target_operations/common.py
  src/mcpm/utils/config.py
  src/mcpm/utils/scope.py
  tests/conftest.py
  tests/test_add.py
  tests/test_clients/test_windsurf.py
  tests/test_remove.py
  tests/test_stash_pop.py
Labels: Review effort 3/5

#188 mark some servers as archived
  mcp-registry/schema/server-schema.json
  mcp-registry/servers/aws-kb-retrieval.json
  mcp-registry/servers/brave-search.json
  mcp-registry/servers/everart.json
  mcp-registry/servers/git.json
  mcp-registry/servers/github.json
  mcp-registry/servers/gitlab.json
  mcp-registry/servers/google-drive.json
  mcp-registry/servers/google-maps.json
  mcp-registry/servers/postgresql.json
  mcp-registry/servers/puppeteer.json
  mcp-registry/servers/sentry.json
  mcp-registry/servers/slack.json
  mcp-registry/servers/sqlite.json
  pages/registry/index.html
  src/mcpm/commands/info.py
Labels: Review effort 2/5, codex-review

#191 chore: support lucien deeplink in registry page
  pages/_includes/lucien-servers.js
  pages/registry/index.html
Labels: Review effort 3/5, Possible security concern

#193 chore: Update broken links and folder structure in mcp-registry/README.md
  mcp-registry/README.md
Labels: Review effort 2/5, codex-review
