Repository pathintegral-institute/mcpm.sh, pull requests merged in 2025-08, with the labels that each got.

#232 chore: Add Boikot MCP Server
  mcp-registry/servers/boikot-mcp.json
Labels: Review effort 2/5

#231 sync mcp.science servers
  mcp-registry/servers/gpaw-computation.json
  mcp-registry/servers/nemad.json
  mcp-registry/servers/netket.json
  mcp-registry/servers/timer.json
  mcp-registry/servers/tinydb.json
  pyproject.toml
  uv.lock
Labels: Review effort 2/5, codex-review-completed, Possible security concern

#245 [generate_manifest] let issue creation trigger the workflow
  .github/workflows/generate-manifest.yml
Labels: Review effort 2/5, Possible security concern
